services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mungo
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: kudos-feedback
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./setup:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
    driver: local
